"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 23:46:49.978636
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_type', sa.String(length=40), nullable=True),
    sa.Column('prefecture', sa.String(length=40), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('address_normalized', sa.String(length=300), nullable=True),
    sa.Column('building_name', sa.String(length=300), nullable=True),
    sa.Column('layout', sa.String(length=20), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('land_area_m2', sa.Float(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('built_year', sa.Integer(), nullable=True),
    sa.Column('current_status', sa.String(length=20), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('adapter', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('adapter_status', sa.String(length=20), nullable=False),
    sa.Column('adapter_diagnostic', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_settings',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('workspace_id', 'key')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('research_status', sa.String(length=30), nullable=False),
    sa.Column('visit_date', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'listing_id')
    )
    op.create_table('listing_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('external_listing_id', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('property_type', sa.String(length=40), nullable=True),
    sa.Column('prefecture', sa.String(length=40), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('building_name', sa.String(length=300), nullable=True),
    sa.Column('price_yen', sa.Integer(), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('land_area_m2', sa.Float(), nullable=True),
    sa.Column('layout', sa.String(length=20), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('built_year', sa.Integer(), nullable=True),
    sa.Column('station', sa.String(length=100), nullable=True),
    sa.Column('walk_minutes', sa.Integer(), nullable=True),
    sa.Column('observation_status', sa.String(length=20), nullable=False),
    sa.Column('url_status', sa.String(length=20), nullable=False),
    sa.Column('raw_enums', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=False),
    sa.Column('manual_import', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'external_listing_id', name='uq_source_site_external')
    )
    with op.batch_alter_table('listing_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_sources_listing_id'), ['listing_id'], unique=False)

    op.create_table('match_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_a_id', sa.Integer(), nullable=False),
    sa.Column('listing_b_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_a_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['listing_b_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_a_id', 'listing_b_id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_listing_id'), ['listing_id'], unique=False)

    op.create_table('search_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('condition_current_version', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_startup_run_at', sa.DateTime(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('paused_reason', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_tasks', schema=None) as batch_op:
        batch_op.create_index('uq_task_name_active', ['workspace_id', 'name'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('site_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('account_alias', sa.String(length=200), nullable=False),
    sa.Column('profile_path', sa.String(length=1000), nullable=False),
    sa.Column('login_status', sa.String(length=30), nullable=False),
    sa.Column('auto_search_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_path')
    )
    op.create_table('site_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('permission_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'permission_type')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name')
    )
    op.create_table('listing_tags',
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('listing_id', 'tag_id')
    )
    op.create_table('search_condition_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('condition_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['search_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'version')
    )
    op.create_table('search_task_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('site_specific_config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['site_accounts.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['search_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'site_id')
    )
    op.create_table('task_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_no', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('account_alias', sa.String(length=200), nullable=True),
    sa.Column('condition_version', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('queued_at', sa.DateTime(), nullable=False),
    sa.Column('not_before', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=20), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('cancel_reason', sa.String(length=200), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('changed_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('not_found_count', sa.Integer(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('unsupported_conditions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['site_accounts.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['search_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_no')
    )
    with op.batch_alter_table('task_runs', schema=None) as batch_op:
        batch_op.create_index('ix_task_runs_status', ['status'], unique=False)
        batch_op.create_index('ix_task_runs_task', ['task_id'], unique=False)

    op.create_table('listing_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('old_price_yen', sa.Integer(), nullable=True),
    sa.Column('new_price_yen', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['task_runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['listing_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_events_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_events_source_id'), ['source_id'], unique=False)
        batch_op.create_index('ix_listing_events_type_created', ['event_type', 'created_at'], unique=False)

    op.create_table('listing_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('price_yen', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary_hash', sa.String(length=64), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['task_runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['listing_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_snapshots_source_id'), ['source_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.String(length=50), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('message_key', sa.String(length=100), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['site_accounts.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['task_runs.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['search_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message_key', sa.String(length=100), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['task_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_log_entries_run_id'), ['run_id'], unique=False)

    op.create_table('run_results',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('is_changed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['task_runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['listing_sources.id'], ),
    sa.PrimaryKeyConstraint('run_id', 'source_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_results')
    with op.batch_alter_table('run_log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_log_entries_run_id'))

    op.drop_table('run_log_entries')
    op.drop_table('notifications')
    with op.batch_alter_table('listing_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_snapshots_source_id'))

    op.drop_table('listing_snapshots')
    with op.batch_alter_table('listing_events', schema=None) as batch_op:
        batch_op.drop_index('ix_listing_events_type_created')
        batch_op.drop_index(batch_op.f('ix_listing_events_source_id'))
        batch_op.drop_index(batch_op.f('ix_listing_events_listing_id'))

    op.drop_table('listing_events')
    with op.batch_alter_table('task_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_task_runs_task')
        batch_op.drop_index('ix_task_runs_status')

    op.drop_table('task_runs')
    op.drop_table('search_task_sites')
    op.drop_table('search_condition_versions')
    op.drop_table('listing_tags')
    op.drop_table('tags')
    op.drop_table('site_permissions')
    op.drop_table('site_accounts')
    with op.batch_alter_table('search_tasks', schema=None) as batch_op:
        batch_op.drop_index('uq_task_name_active', sqlite_where=sa.text('deleted_at IS NULL'))

    op.drop_table('search_tasks')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_listing_id'))

    op.drop_table('notes')
    op.drop_table('match_candidates')
    with op.batch_alter_table('listing_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_sources_listing_id'))

    op.drop_table('listing_sources')
    op.drop_table('favorites')
    op.drop_table('app_settings')
    op.drop_table('workspaces')
    op.drop_table('sites')
    op.drop_table('listings')
    # ### end Alembic commands ###
