"""run progress

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 22:13:52.137256
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress_stage', sa.String(length=20), nullable=False, server_default='queued'))
        batch_op.add_column(sa.Column('progress_pct', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('expected_total', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wait_reason', sa.String(length=40), nullable=True))

    # Runs that already finished before this migration are complete as far as progress is concerned.
    op.execute("UPDATE task_runs SET progress_stage = 'done', progress_pct = 100 "
               "WHERE status NOT IN ('queued', 'running')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_runs', schema=None) as batch_op:
        batch_op.drop_column('wait_reason')
        batch_op.drop_column('expected_total')
        batch_op.drop_column('progress_pct')
        batch_op.drop_column('progress_stage')

    # ### end Alembic commands ###
