"""site rule checks

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-24 22:40:00.849153
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_rule_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('robots_url', sa.String(length=500), nullable=True),
    sa.Column('robots_findings', sa.JSON(), nullable=False),
    sa.Column('terms_findings', sa.JSON(), nullable=False),
    sa.Column('fetch_errors', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_rule_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_rule_checks_site_id'), ['site_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_rule_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_rule_checks_site_id'))

    op.drop_table('site_rule_checks')
    # ### end Alembic commands ###
