"""rental support

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-25 22:14:54.640325
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deal_type', sa.String(length=10), server_default='buy', nullable=False))
        batch_op.add_column(sa.Column('management_fee_yen', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deposit_yen', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('key_money_yen', sa.Integer(), nullable=True))

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deal_type', sa.String(length=10), server_default='buy', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('deal_type')

    with op.batch_alter_table('listing_sources', schema=None) as batch_op:
        batch_op.drop_column('key_money_yen')
        batch_op.drop_column('deposit_yen')
        batch_op.drop_column('management_fee_yen')
        batch_op.drop_column('deal_type')

    # ### end Alembic commands ###
