"""ai investment assessment

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-28 21:29:15.981899
"""
from alembic import op
import sqlalchemy as sa


revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_provider_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_type', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('key_reference', sa.String(length=64), nullable=True),
    sa.Column('key_last4', sa.String(length=8), nullable=True),
    sa.Column('limits_json', sa.JSON(), nullable=False),
    sa.Column('allowed_fields_json', sa.JSON(), nullable=False),
    sa.Column('pricing_json', sa.JSON(), nullable=False),
    sa.Column('last_test_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_status', sa.String(length=40), nullable=True),
    sa.Column('last_test_detail', sa.JSON(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('thresholds_json', sa.JSON(), nullable=False),
    sa.Column('assumptions_json', sa.JSON(), nullable=False),
    sa.Column('owner_occupancy_preferences_json', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_config_id', sa.Integer(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('provider_type', sa.String(length=20), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('input_units', sa.Integer(), nullable=True),
    sa.Column('output_units', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('cost_currency', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('correlation_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['provider_config_id'], ['ai_provider_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_records_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_records_provider_config_id'), ['provider_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_records_requested_at'), ['requested_at'], unique=False)

    op.create_table('investment_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('primary_label', sa.String(length=30), nullable=False),
    sa.Column('rule_label', sa.String(length=30), nullable=False),
    sa.Column('secondary_labels_json', sa.JSON(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('rationale_json', sa.JSON(), nullable=False),
    sa.Column('risks_json', sa.JSON(), nullable=False),
    sa.Column('missing_fields_json', sa.JSON(), nullable=False),
    sa.Column('calculations_json', sa.JSON(), nullable=False),
    sa.Column('sources_json', sa.JSON(), nullable=False),
    sa.Column('input_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('input_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('rule_version', sa.String(length=20), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('model_provider', sa.String(length=20), nullable=True),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('model_version', sa.String(length=200), nullable=True),
    sa.Column('ai_error', sa.String(length=60), nullable=True),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('correlation_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['investment_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investment_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investment_assessments_input_snapshot_hash'), ['input_snapshot_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_investment_assessments_listing_id'), ['listing_id'], unique=False)

    op.create_table('investment_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('values_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id')
    )
    op.create_table('investment_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('user_label', sa.String(length=30), nullable=False),
    sa.Column('user_tags_json', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['investment_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investment_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investment_overrides_assessment_id'), ['assessment_id'], unique=False)

    # Plain ALTER TABLE ADD COLUMN: SQLite supports it for these columns, so the task table is not rebuilt.
    op.add_column('search_tasks', sa.Column('assess_after_run', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('search_tasks', sa.Column('assess_profile_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_tasks', schema=None) as batch_op:
        batch_op.drop_column('assess_profile_id')
        batch_op.drop_column('assess_after_run')

    with op.batch_alter_table('investment_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investment_overrides_assessment_id'))

    op.drop_table('investment_overrides')
    op.drop_table('investment_inputs')
    with op.batch_alter_table('investment_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investment_assessments_listing_id'))
        batch_op.drop_index(batch_op.f('ix_investment_assessments_input_snapshot_hash'))

    op.drop_table('investment_assessments')
    with op.batch_alter_table('ai_usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_records_requested_at'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_records_provider_config_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_records_assessment_id'))

    op.drop_table('ai_usage_records')
    op.drop_table('investment_profiles')
    op.drop_table('ai_provider_configs')
    # ### end Alembic commands ###
